/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.mymix;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mymix.MymixFactory
 * @model kind="package"
 * @generated
 */
public interface MymixPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mymix";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Mymix";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mymix";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MymixPackage eINSTANCE = org.xtext.example.mydsl.mymix.impl.MymixPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.MachineImpl <em>Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.MachineImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getMachine()
   * @generated
   */
  int MACHINE = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__OPERATIONS = 0;

  /**
   * The number of structural features of the '<em>Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.OperationImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 1;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.PutImpl <em>Put</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.PutImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPut()
   * @generated
   */
  int PUT = 2;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__QUANTITY = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__CUP = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__FILTER = OPERATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Wait</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT__WAIT = OPERATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Put</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.WaitImpl <em>Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.WaitImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getWait()
   * @generated
   */
  int WAIT = 3;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT__TIME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.FilterImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 4;

  /**
   * The feature id for the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__FILTER = 0;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.CupImpl <em>Cup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.CupImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCup()
   * @generated
   */
  int CUP = 5;

  /**
   * The feature id for the '<em><b>Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP__CUP = 0;

  /**
   * The number of structural features of the '<em>Cup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mymix.impl.QuantityImpl <em>Quantity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mymix.impl.QuantityImpl
   * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getQuantity()
   * @generated
   */
  int QUANTITY = 6;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANTITY__QUANTITY = 0;

  /**
   * The number of structural features of the '<em>Quantity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANTITY_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Machine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine</em>'.
   * @see org.xtext.example.mydsl.mymix.Machine
   * @generated
   */
  EClass getMachine();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.Machine#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.mymix.Machine#getOperations()
   * @see #getMachine()
   * @generated
   */
  EReference getMachine_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.example.mydsl.mymix.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Put <em>Put</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put</em>'.
   * @see org.xtext.example.mydsl.mymix.Put
   * @generated
   */
  EClass getPut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getQuantity()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Quantity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getCup()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Cup();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.mymix.Put#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getFilter()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Filter();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mymix.Put#getWait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Wait</em>'.
   * @see org.xtext.example.mydsl.mymix.Put#getWait()
   * @see #getPut()
   * @generated
   */
  EReference getPut_Wait();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Wait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait</em>'.
   * @see org.xtext.example.mydsl.mymix.Wait
   * @generated
   */
  EClass getWait();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Wait#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.example.mydsl.mymix.Wait#getTime()
   * @see #getWait()
   * @generated
   */
  EAttribute getWait_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Filter#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.mymix.Filter#getFilter()
   * @see #getFilter()
   * @generated
   */
  EAttribute getFilter_Filter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Cup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Cup
   * @generated
   */
  EClass getCup();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Cup#getCup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cup</em>'.
   * @see org.xtext.example.mydsl.mymix.Cup#getCup()
   * @see #getCup()
   * @generated
   */
  EAttribute getCup_Cup();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mymix.Quantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Quantity
   * @generated
   */
  EClass getQuantity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mymix.Quantity#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.mymix.Quantity#getQuantity()
   * @see #getQuantity()
   * @generated
   */
  EAttribute getQuantity_Quantity();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MymixFactory getMymixFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.MachineImpl <em>Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.MachineImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getMachine()
     * @generated
     */
    EClass MACHINE = eINSTANCE.getMachine();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE__OPERATIONS = eINSTANCE.getMachine_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.OperationImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.PutImpl <em>Put</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.PutImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getPut()
     * @generated
     */
    EClass PUT = eINSTANCE.getPut();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__QUANTITY = eINSTANCE.getPut_Quantity();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__CUP = eINSTANCE.getPut_Cup();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__FILTER = eINSTANCE.getPut_Filter();

    /**
     * The meta object literal for the '<em><b>Wait</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT__WAIT = eINSTANCE.getPut_Wait();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.WaitImpl <em>Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.WaitImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getWait()
     * @generated
     */
    EClass WAIT = eINSTANCE.getWait();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT__TIME = eINSTANCE.getWait_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.FilterImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER__FILTER = eINSTANCE.getFilter_Filter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.CupImpl <em>Cup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.CupImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getCup()
     * @generated
     */
    EClass CUP = eINSTANCE.getCup();

    /**
     * The meta object literal for the '<em><b>Cup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUP__CUP = eINSTANCE.getCup_Cup();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mymix.impl.QuantityImpl <em>Quantity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mymix.impl.QuantityImpl
     * @see org.xtext.example.mydsl.mymix.impl.MymixPackageImpl#getQuantity()
     * @generated
     */
    EClass QUANTITY = eINSTANCE.getQuantity();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUANTITY__QUANTITY = eINSTANCE.getQuantity_Quantity();

  }

} //MymixPackage
